name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Run zig fmt
        if: matrix.os == 'macos-latest'
        run: zig fmt --check .

      - name: Run zig build test
        run: |
          zig build test --summary all
          zig build golden --summary all

      - name: Run zig build
        run: |
          zig build
          echo "$(pwd)/zig-out/bin" >> "$GITHUB_PATH"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Puppeteer tests
        run: |
          cd tests/puppeteer
          bun install
          bun test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: npm install
        run: |
          cd vscode
          npm install

      - name: npm test
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd vscode
          xvfb-run -a npm run test

      - name: npm test
        if: matrix.os == 'macos-latest'
        run: |
          cd vscode
          npm run test
